### ISSUE TITLE
This is beautiful! Let's get this live!

### ISSUE THREAD

**Issue by hubdotcom** [jsdelivr/beta.jsdelivr.com#29]
This could be the marketing push that jsDelivr has been waiting for, let's get this launched. Where can we start?

**Comment by jimaek** [comment]
I have something special planned for this. It needs some time

**Comment by hubdotcom** [comment]
![Move fast and break things!](https://cloud.githubusercontent.com/assets/5274747/7138604/b9307f7a-e2c1-11e4-8de8-dffc630355c3.jpg)

**Comment by jimaek** [comment]
I agree, but not in this case. The backend will be the same but the design will change.  I have a guy working on it.

**Comment by MartinKolarik** [comment]
>the design will change

Again? What changes do you have in mind?
